<a href="https://colab.research.google.com/github/May-Myat-Noe-Oo/pytorch-youtube-tutorial/blob/main/Intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [ ]:
!pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.9.0
aiofiles                              24.1.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.12.15
aiosignal                             1.4.0
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.11.2
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
anywidget                             0.9.18
argon2-cffi                           25.1.0
argon2-cffi-bindings                  25.1.0
array_record                          0.7.2
arviz                                 0.22.0
astropy                               7.1.0
astropy

**LISTS**

In [1]:
lists = [[1,2,3,4],[5,6,7,8,9,10]]
lists

[[1, 2, 3, 4], [5, 6, 7, 8, 9, 10]]

**Numpys**

In [2]:
import numpy as np


In [3]:
np1=np.random.rand(3,4)
np1

array([[0.60558902, 0.71314114, 0.86386626, 0.78297351],
       [0.90989282, 0.07192459, 0.07990331, 0.85768332],
       [0.49503661, 0.44900574, 0.50973447, 0.47348542]])

In [4]:
np1.dtype

dtype('float64')

**Tensors**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0646,  1.0051,  1.9942,  1.9335],
        [ 0.0542,  0.4227, -1.5349,  0.0658],
        [-0.5264,  1.2017, -0.0025,  1.8819]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
tensor_3d.dtype

torch.float32

In [9]:
tensor_2d = torch.tensor(np1)
tensor_2d

tensor([[0.6056, 0.7131, 0.8639, 0.7830],
        [0.9099, 0.0719, 0.0799, 0.8577],
        [0.4950, 0.4490, 0.5097, 0.4735]], dtype=torch.float64)

In [4]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch = my_torch.reshape(2,-1)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch = my_torch.reshape(-1,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch1 = my_torch.reshape(2,5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch[1] = 35

In [7]:
my_torch1

tensor([[ 0, 35,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

**Slice**

In [8]:
my_torch1[:,1]

tensor([35,  6])

In [9]:
my_torch1[:,2]

tensor([2, 7])

In [5]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

**Addition**

In [6]:
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [7]:
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [8]:
tensor_a.add(tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [9]:
#Reassignment
tensor_a.add_(tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [10]:
tensor_a

tensor([ 7,  9, 11, 13, 15])

**Subtraction**

In [11]:
tensor_c = tensor_a - tensor_b
tensor_c

tensor([1, 2, 3, 4, 5])

In [13]:
torch.subtract(tensor_b , tensor_c)

tensor([5, 5, 5, 5, 5])

In [14]:
tensor_b

tensor([ 6,  7,  8,  9, 10])

In [15]:
tensor_c

tensor([1, 2, 3, 4, 5])

**Multiplication Element-Wise operation**

In [16]:
tensor_b * tensor_c

tensor([ 6, 14, 24, 36, 50])

In [18]:
torch.mul(tensor_c,tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [19]:
tensor_c.mul(tensor_b)

tensor([ 6, 14, 24, 36, 50])

**Division**

In [20]:
tensor_b / tensor_c

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [21]:
torch.div(tensor_b, tensor_c)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [22]:
tensor_b.div(tensor_c)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

**Modulus**

In [23]:
tensor_b % tensor_c

tensor([0, 1, 2, 1, 0])

Exponent/**Power**

In [25]:
torch.pow(tensor_b,tensor_c)

tensor([     6,     49,    512,   6561, 100000])

In [26]:
tensor_b.pow(tensor_c)

tensor([     6,     49,    512,   6561, 100000])